#!/usr/bin/with-contenv bashio
# shellcheck shell=bash

# ==============================================================================
# PiAware Add-on for Home Assistant
# Starts dump1090-fa, piaware, and lighttpd (SkyAware)
# ==============================================================================

declare feeder_id
declare latitude
declare longitude
declare altitude_ft
declare receiver_type
declare gain
declare allow_mlat
declare allow_modeac
declare rtlsdr_ppm
declare rtlsdr_device_serial

# --- Read configuration ---
feeder_id=$(bashio::config 'feeder_id' '')
latitude=$(bashio::config 'latitude')
longitude=$(bashio::config 'longitude')
altitude_ft=$(bashio::config 'altitude_ft' '0')
receiver_type=$(bashio::config 'receiver_type')
gain=$(bashio::config 'gain')
allow_mlat=$(bashio::config 'allow_mlat')
allow_modeac=$(bashio::config 'allow_modeac')
rtlsdr_ppm=$(bashio::config 'rtlsdr_ppm' '0')
rtlsdr_device_serial=$(bashio::config 'rtlsdr_device_serial' '')

# --- Persistent data directory ---
mkdir -p /data/piaware

# --- Handle feeder ID ---
# Priority: config option > saved file > auto-generate
if [ -n "${feeder_id}" ]; then
    bashio::log.info "Using feeder ID from configuration: ${feeder_id}"
elif [ -f /data/piaware/feeder-id ]; then
    feeder_id=$(cat /data/piaware/feeder-id)
    bashio::log.info "Using saved feeder ID: ${feeder_id}"
else
    bashio::log.info "No feeder ID found, will be auto-generated by PiAware"
fi

# --- Configure PiAware ---
bashio::log.info "Configuring PiAware..."

if [ -n "${feeder_id}" ]; then
    piaware-config feeder-id "${feeder_id}"
fi

piaware-config receiver-type "${receiver_type}"
piaware-config receiver-host localhost
piaware-config receiver-port 30005

if bashio::var.true "${allow_mlat}"; then
    piaware-config allow-mlat yes
else
    piaware-config allow-mlat no
fi

if bashio::var.true "${allow_modeac}"; then
    piaware-config allow-modeac yes
else
    piaware-config allow-modeac no
fi

# --- Build dump1090-fa command-line arguments ---
DUMP1090_ARGS=(
    --device-type rtlsdr
    --net
    --net-sbs-port 30003
    --net-bi-port 30004,30104
    --net-bo-port 30005
    --net-ro-port 30002
    --lat "${latitude}"
    --lon "${longitude}"
    --fix
    --json-location-accuracy 1
    --write-json /run/dump1090-fa
    --write-json-every 1
    --quiet
)

# Gain setting
if [ "${gain}" = "max" ]; then
    DUMP1090_ARGS+=(--gain -10)
elif [ "${gain}" = "auto" ]; then
    DUMP1090_ARGS+=(--gain -1)
else
    DUMP1090_ARGS+=(--gain "${gain}")
fi

# PPM correction
if [ "${rtlsdr_ppm}" != "0" ]; then
    DUMP1090_ARGS+=(--ppm "${rtlsdr_ppm}")
fi

# Specific device serial
if [ -n "${rtlsdr_device_serial}" ]; then
    DUMP1090_ARGS+=(--device "${rtlsdr_device_serial}")
fi

# Mode A/C
if bashio::var.true "${allow_modeac}"; then
    DUMP1090_ARGS+=(--modeac)
fi

# MLAT Beast output port
DUMP1090_ARGS+=(--net-bo-port 30105)

# --- Graceful shutdown handler ---
cleanup() {
    bashio::log.info "Shutting down..."
    kill "${DUMP1090_PID}" 2>/dev/null
    kill "${LIGHTTPD_PID}" 2>/dev/null
    kill "${PIAWARE_PID}" 2>/dev/null
    wait
    exit 0
}
trap cleanup SIGTERM SIGINT

# --- Start dump1090-fa ---
bashio::log.info "Starting dump1090-fa..."
bashio::log.info "  Latitude: ${latitude}"
bashio::log.info "  Longitude: ${longitude}"
bashio::log.info "  Gain: ${gain}"
bashio::log.info "  Receiver type: ${receiver_type}"

dump1090-fa "${DUMP1090_ARGS[@]}" &
DUMP1090_PID=$!

# Wait for dump1090 to start
sleep 3

if ! kill -0 "${DUMP1090_PID}" 2>/dev/null; then
    bashio::log.error "dump1090-fa failed to start!"
    exit 1
fi
bashio::log.info "dump1090-fa started (PID: ${DUMP1090_PID})"

# --- Start lighttpd (SkyAware web server) ---
bashio::log.info "Starting lighttpd for SkyAware..."
lighttpd -f /etc/lighttpd/lighttpd.conf -D &
LIGHTTPD_PID=$!

# --- Start PiAware ---
bashio::log.info "Starting PiAware..."
piaware -plainlog -statusfile /run/piaware/status.json &
PIAWARE_PID=$!

# --- Capture feeder ID after startup ---
(
    sleep 15
    if [ ! -f /data/piaware/feeder-id ]; then
        # Try to capture from PiAware's config
        captured_id=""
        if [ -f /var/cache/piaware/feeder_id ]; then
            captured_id=$(cat /var/cache/piaware/feeder_id)
        elif command -v piaware-config > /dev/null; then
            captured_id=$(piaware-config -show feeder-id 2>/dev/null || true)
        fi
        if [ -n "${captured_id}" ] && [ "${captured_id}" != "not set" ]; then
            echo "${captured_id}" > /data/piaware/feeder-id
            bashio::log.info "Feeder ID captured and saved: ${captured_id}"
        fi
    fi
) &

# --- Wait for any process to exit ---
bashio::log.info "All processes started, monitoring..."

wait -n "${DUMP1090_PID}" "${LIGHTTPD_PID}" "${PIAWARE_PID}"

# If any process exits, shut everything down
bashio::log.warning "A process exited unexpectedly, shutting down..."
cleanup
