#!/usr/bin/with-contenv bashio
# shellcheck shell=bash

# ==============================================================================
# PiAware Add-on for Home Assistant
# Starts dump1090-fa, piaware, and lighttpd (SkyAware)
# ==============================================================================

declare feeder_id
declare gps_source
declare gpsd_host
declare gpsd_port
declare latitude
declare longitude
declare altitude_ft
declare receiver_type
declare gain
declare allow_mlat
declare allow_modeac
declare rtlsdr_ppm
declare rtlsdr_device_serial
declare log_level
declare gps_coordinate_updates
declare gps_coordinate_update_interval

# Temp files for coordinating planned dump1090 restarts
COORD_UPDATE_FILE="/tmp/piaware_coord_update"
DUMP1090_PID_FILE="/tmp/dump1090.pid"

# --- Read configuration ---
log_level=$(bashio::config 'log_level' 'info')
bashio::log.level "${log_level}"

feeder_id=$(bashio::config 'feeder_id' '')
gps_source=$(bashio::config 'gps_source' 'manual')
altitude_ft=$(bashio::config 'altitude_ft' '0')
gps_coordinate_updates=$(bashio::config 'gps_coordinate_updates' 'false')
gps_coordinate_update_interval=$(bashio::config 'gps_coordinate_update_interval' '60')

bashio::log.debug "Configuration: gps_source='${gps_source}' altitude_ft='${altitude_ft}' gps_coordinate_updates='${gps_coordinate_updates}'"

# --- Resolve coordinates ---
if [ "${gps_source}" = "gpsd" ]; then
    gpsd_host=$(bashio::config 'gpsd_host' '')
    gpsd_port=$(bashio::config 'gpsd_port' '2947')
    [ -z "${gpsd_host}" ] && gpsd_host="homeassistant.local"

    bashio::log.info "GPS source: gpsd (${gpsd_host}:${gpsd_port})"

    fix=""
    for attempt in 1 2 3 4 5; do
        bashio::log.info "Querying gpsd for fix (attempt ${attempt}/5)..."
        raw=$(gpsd_client --host "${gpsd_host}" --port "${gpsd_port}" --count 30 --timeout 30 2>/dev/null || true)
        bashio::log.trace "gpsd_client raw output: ${raw}"
        fix=$(echo "${raw}" | jq -c 'select(.class=="TPV") | select(.mode>=2) | select(.lat!=null and .lon!=null)' | tail -1)
        bashio::log.debug "Parsed fix: ${fix:-<none>}"
        [ -n "${fix}" ] && break
        [ "${attempt}" -lt 5 ] && bashio::log.info "No fix yet, retrying in 15s..." && sleep 15
    done

    if [ -z "${fix}" ]; then
        bashio::log.warning "Could not obtain a GPS fix from gpsd after 5 attempts. Starting without coordinates — range rings and map centering will be unavailable."
        latitude=""
        longitude=""
    else
        latitude=$(echo "${fix}" | jq -r '.lat')
        longitude=$(echo "${fix}" | jq -r '.lon')

        if [ -z "${latitude}" ] || [ "${latitude}" = "null" ] || [ -z "${longitude}" ] || [ "${longitude}" = "null" ]; then
            bashio::log.warning "gpsd returned a fix but lat/lon were null. Starting without coordinates."
            latitude=""
            longitude=""
        else
            bashio::log.info "Coordinates from gpsd: lat=${latitude}, lon=${longitude}"
        fi
    fi
else
    latitude=$(bashio::config 'latitude' '')
    longitude=$(bashio::config 'longitude' '')

    if [ -z "${latitude}" ] || [ -z "${longitude}" ]; then
        bashio::log.fatal "latitude and longitude are required when gps_source is 'manual'."
        exit 1
    fi
fi

receiver_type=$(bashio::config 'receiver_type')
gain=$(bashio::config 'gain')
allow_mlat=$(bashio::config 'allow_mlat')
allow_modeac=$(bashio::config 'allow_modeac')
rtlsdr_ppm=$(bashio::config 'rtlsdr_ppm' '0')
rtlsdr_device_serial=$(bashio::config 'rtlsdr_device_serial' '')

# --- Persistent data directory ---
mkdir -p /data/piaware

# --- Handle feeder ID ---
# Priority: config option > saved file > auto-generate
if [ -n "${feeder_id}" ]; then
    bashio::log.info "Using feeder ID from configuration: ${feeder_id}"
elif [ -f /data/piaware/feeder-id ]; then
    feeder_id=$(cat /data/piaware/feeder-id)
    bashio::log.info "Using saved feeder ID: ${feeder_id}"
else
    bashio::log.info "No feeder ID found, will be auto-generated by PiAware"
fi

# --- Configure PiAware ---
bashio::log.info "Configuring PiAware..."

if [ -n "${feeder_id}" ]; then
    piaware-config feeder-id "${feeder_id}"
fi

piaware-config receiver-type "${receiver_type}"
piaware-config receiver-host localhost
piaware-config receiver-port 30005

if bashio::var.true "${allow_mlat}"; then
    piaware-config allow-mlat yes
else
    piaware-config allow-mlat no
fi

if bashio::var.true "${allow_modeac}"; then
    piaware-config allow-modeac yes
else
    piaware-config allow-modeac no
fi

# --- Build static dump1090-fa arguments (everything except lat/lon) ---
DUMP1090_STATIC_ARGS=(
    --device-type rtlsdr
    --net
    --net-sbs-port 30003
    --net-bi-port 30004,30104
    --net-bo-port 30005
    --net-ro-port 30002
    --net-bo-port 30105
    --fix
    --json-location-accuracy 1
    --write-json /run/dump1090-fa
    --write-json-every 1
    --quiet
)

# Gain setting
if [ "${gain}" = "max" ]; then
    DUMP1090_STATIC_ARGS+=(--gain -10)
elif [ "${gain}" = "auto" ]; then
    DUMP1090_STATIC_ARGS+=(--gain -1)
else
    DUMP1090_STATIC_ARGS+=(--gain "${gain}")
fi

# PPM correction
if [ "${rtlsdr_ppm}" != "0" ]; then
    DUMP1090_STATIC_ARGS+=(--ppm "${rtlsdr_ppm}")
fi

# Specific device serial
if [ -n "${rtlsdr_device_serial}" ]; then
    DUMP1090_STATIC_ARGS+=(--device "${rtlsdr_device_serial}")
fi

# Mode A/C
if bashio::var.true "${allow_modeac}"; then
    DUMP1090_STATIC_ARGS+=(--modeac)
fi

# --- start_dump1090 <lat> <lon> ---
# Starts dump1090-fa, writes its PID to DUMP1090_PID_FILE, and prints the PID.
start_dump1090() {
    local lat="$1"
    local lon="$2"
    local args=("${DUMP1090_STATIC_ARGS[@]}")

    if [ -n "${lat}" ] && [ -n "${lon}" ]; then
        args+=(--lat "${lat}" --lon "${lon}")
    else
        bashio::log.warning "No coordinates available — range rings and map centering will be unavailable."
    fi

    bashio::log.debug "dump1090-fa args: ${args[*]}"
    dump1090-fa "${args[@]}" &
    local pid=$!
    echo "${pid}" > "${DUMP1090_PID_FILE}"
    echo "${pid}"
}

# --- GPS coordinate monitor loop ---
# Polls gpsd on the configured interval. When the position changes by more
# than ~100m (0.001 degrees), writes the new coords to COORD_UPDATE_FILE and
# kills the current dump1090-fa so the main loop can restart it.
gps_monitor_loop() {
    local current_lat="${latitude}"
    local current_lon="${longitude}"

    bashio::log.info "GPS coordinate monitor started (interval: ${gps_coordinate_update_interval}s)"

    while true; do
        sleep "${gps_coordinate_update_interval}"

        raw=$(gpsd_client --host "${gpsd_host}" --port "${gpsd_port}" --count 30 --timeout 30 2>/dev/null || true)
        bashio::log.trace "GPS monitor gpsd_client output: ${raw}"
        fix=$(echo "${raw}" | jq -c 'select(.class=="TPV") | select(.mode>=2) | select(.lat!=null and .lon!=null)' | tail -1)

        if [ -z "${fix}" ]; then
            bashio::log.debug "GPS monitor: no fix available"
            continue
        fi

        new_lat=$(echo "${fix}" | jq -r '.lat')
        new_lon=$(echo "${fix}" | jq -r '.lon')

        # Check if position changed beyond ~100m threshold (0.001 degrees)
        changed=$(awk -v nlat="${new_lat}" -v clat="${current_lat:-0}" \
                       -v nlon="${new_lon}" -v clon="${current_lon:-0}" \
                  'BEGIN {
                       dlat = nlat - clat; if (dlat < 0) dlat = -dlat
                       dlon = nlon - clon; if (dlon < 0) dlon = -dlon
                       print (dlat > 0.001 || dlon > 0.001) ? "yes" : "no"
                   }')

        if [ "${changed}" = "yes" ]; then
            bashio::log.info "Location changed: (${current_lat},${current_lon}) -> (${new_lat},${new_lon}) — restarting dump1090-fa"
            current_lat="${new_lat}"
            current_lon="${new_lon}"

            echo "${new_lat} ${new_lon}" > "${COORD_UPDATE_FILE}"
            dump1090_pid=$(cat "${DUMP1090_PID_FILE}" 2>/dev/null)
            [ -n "${dump1090_pid}" ] && kill "${dump1090_pid}" 2>/dev/null
        else
            bashio::log.debug "GPS monitor: position unchanged (lat=${new_lat}, lon=${new_lon})"
        fi
    done
}

# --- Graceful shutdown handler ---
GPS_MONITOR_PID=""

cleanup() {
    bashio::log.info "Shutting down..."
    [ -n "${GPS_MONITOR_PID}" ] && kill "${GPS_MONITOR_PID}" 2>/dev/null
    kill "${DUMP1090_PID}" 2>/dev/null
    kill "${LIGHTTPD_PID}" 2>/dev/null
    kill "${PIAWARE_PID}" 2>/dev/null
    rm -f "${COORD_UPDATE_FILE}" "${DUMP1090_PID_FILE}"
    wait
    exit 0
}
trap cleanup SIGTERM SIGINT

# --- Start dump1090-fa ---
bashio::log.info "Starting dump1090-fa..."
bashio::log.info "  Latitude:      ${latitude:-<not set>}"
bashio::log.info "  Longitude:     ${longitude:-<not set>}"
bashio::log.info "  Gain:          ${gain}"
bashio::log.info "  Receiver type: ${receiver_type}"

DUMP1090_PID=$(start_dump1090 "${latitude}" "${longitude}")

sleep 3

if ! kill -0 "${DUMP1090_PID}" 2>/dev/null; then
    bashio::log.error "dump1090-fa failed to start!"
    exit 1
fi
bashio::log.info "dump1090-fa started (PID: ${DUMP1090_PID})"

# --- Start lighttpd (SkyAware web server) ---
bashio::log.info "Starting lighttpd for SkyAware..."
lighttpd -f /etc/lighttpd/lighttpd.conf -D &
LIGHTTPD_PID=$!

# --- Start PiAware ---
bashio::log.info "Starting PiAware..."
piaware -plainlog -statusfile /run/piaware/status.json &
PIAWARE_PID=$!

# --- Capture feeder ID after startup ---
(
    sleep 15
    if [ ! -f /data/piaware/feeder-id ]; then
        captured_id=""
        if [ -f /var/cache/piaware/feeder_id ]; then
            captured_id=$(cat /var/cache/piaware/feeder_id)
        elif command -v piaware-config > /dev/null; then
            captured_id=$(piaware-config -show feeder-id 2>/dev/null || true)
        fi
        if [ -n "${captured_id}" ] && [ "${captured_id}" != "not set" ]; then
            echo "${captured_id}" > /data/piaware/feeder-id
            bashio::log.info "Feeder ID captured and saved: ${captured_id}"
        fi
    fi
) &

# --- Start GPS coordinate monitor (only when using gpsd with updates enabled) ---
if [ "${gps_source}" = "gpsd" ] && bashio::var.true "${gps_coordinate_updates}"; then
    gps_monitor_loop &
    GPS_MONITOR_PID=$!
fi

# --- Monitor processes ---
# dump1090-fa may be intentionally restarted for coordinate updates; lighttpd
# and piaware exiting is always fatal.
bashio::log.info "All processes started, monitoring..."

while true; do
    wait -n "${DUMP1090_PID}" "${LIGHTTPD_PID}" "${PIAWARE_PID}"

    if ! kill -0 "${LIGHTTPD_PID}" 2>/dev/null || ! kill -0 "${PIAWARE_PID}" 2>/dev/null; then
        bashio::log.warning "A critical process exited unexpectedly, shutting down..."
        cleanup
    fi

    if ! kill -0 "${DUMP1090_PID}" 2>/dev/null; then
        if [ -f "${COORD_UPDATE_FILE}" ]; then
            read -r latitude longitude < "${COORD_UPDATE_FILE}"
            rm -f "${COORD_UPDATE_FILE}"
            bashio::log.info "Restarting dump1090-fa with updated coordinates: lat=${latitude}, lon=${longitude}"
            DUMP1090_PID=$(start_dump1090 "${latitude}" "${longitude}")
            sleep 3
            if ! kill -0 "${DUMP1090_PID}" 2>/dev/null; then
                bashio::log.error "dump1090-fa failed to restart after coordinate update!"
                cleanup
            fi
            bashio::log.info "dump1090-fa restarted (PID: ${DUMP1090_PID})"
        else
            bashio::log.warning "dump1090-fa exited unexpectedly, shutting down..."
            cleanup
        fi
    fi
done
